Origin/about
Turt1ePower/fs74-icecream-project17 pull request #11
Opened 2023-01-14 20:02 UTC by MishaHryvinskyi

add origin/about

2023-01-14 20:34 UTC, Turt1ePower commented on src/sass/components/_main-button.scss
> +
тут плюсики какие-то странные надо убрать

2023-01-14 20:34 UTC, Turt1ePower commented on src/sass/components/_main-button.scss
> +
и еще один странный плюсик

2023-01-14 20:41 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +    @media screen and(min-width:$mobile-min) and (max-width:$desktop-max) {
тут надо убрать второе правило, ибо для десктопа тогда не применяется, просто оставь так

@media screen and(min-width:$mobile-min)

2023-01-14 20:46 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        flex-direction: column-reverse;
этого нет в макете, можно убрать

2023-01-14 20:47 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        flex-direction: column-reverse;
там скорее всего просто column

2023-01-14 22:08 UTC, Turt1ePower commented
нужно поменять блок с коровой как в телеграмме рассказал (удалить контентные фотки, весь блок html разметки и стили к фоткам, сделать before на секцию с текстами и задать стили которые я прислал, удалить фотки которые jpg и скачать и загрузить фотки для обычных и ретина экранов для мобилки таблетки и десктопа, подписать их в путь правильно в стилях, заменить цвета на переменные)

2023-01-14 22:10 UTC, Turt1ePower commented
нужно задать все текстовые стили не через миксины, т.к. миксины ломают всё и добавляют повторы на элементы где эти стили уже есть

2023-01-14 22:12 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
для мобилки там в макете написано line-height: 1.76

2023-01-14 22:13 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.58;
для мобилки по макету line-height: 1.62

2023-01-14 22:18 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +.about__title-uppertitle {
маржин который отталкивает заголовки от коровы надо давать тут, а не в одном из заголовков

2023-01-14 22:19 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        margin-bottom: 12px;
маржин надо давать в .about__title-uppertitle

2023-01-14 22:20 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        margin-bottom: 54px;
маржин надо давать в .about__title-uppertitle

2023-01-14 22:27 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
для десктопа там в макете написано line-height: 1.76, вроде от боди унаследует, поэтому можно попробовать убрать и проверить потом

2023-01-14 22:29 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
для таблеткитам в макете написано line-height: 1.76

2023-01-14 22:30 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.91;
по макету там line-height: 1.94;

2023-01-14 22:33 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +    font-family: 'Seymour One';
тут надо в конце дописать же альтернативный шрифт

font-family: 'Seymour One', sans-serif;

2023-01-14 22:39 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        margin-bottom: 24px;
это правило надо закрыть до таблетки или до десктопа, ибо маржин тут перебивает маржин который ты ниже даёшь для десктопа, там по макету 8 для десктопа

2023-01-14 22:40 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
для десктопа там в макете написано line-height: 1.76, вроде от боди унаследует, поэтому можно попробовать убрать и проверить потом

2023-01-14 22:40 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        letter-spacing: 0.04em;
это тоже от боди наследуется, можно убрать

2023-01-14 22:43 UTC, Turt1ePower commented
надо убрать все лишние font-weight: 400; т.к. это значение по-умолчанию для большинства элементов в html

2023-01-14 22:45 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.92;
тут по макету line-height: 1.94;

2023-01-14 22:48 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +        line-height: 1.92;
по макету тут line-height: 1.94;

2023-01-14 22:50 UTC, Turt1ePower requested changes
остальное в лс расписал

2023-01-15 16:35 UTC, MishaHryvinskyi commented on src/sass/components/_main-button.scss
> +
ок

2023-01-15 16:35 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +    @media screen and(min-width:$mobile-min) and (max-width:$desktop-max) {
гаразд. видалив

2023-01-15 16:36 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        flex-direction: column-reverse;
залишив тілmки column

2023-01-15 16:37 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
виправив згідно макету

2023-01-15 16:37 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        line-height: 1.58;
готово

2023-01-15 16:38 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +.about__title-uppertitle {
виправив

2023-01-15 16:39 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        margin-bottom: 12px;
виправив, коли забрав маржин у title

2023-01-15 16:39 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
теж виправив згідно маету

2023-01-15 16:40 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
теж виправив згідно макету

2023-01-15 16:40 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        line-height: 1.75;
ок

2023-01-15 16:40 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +    font-family: 'Seymour One';
добавив альтернативний шрифт

2023-01-15 16:41 UTC, MishaHryvinskyi commented on src/sass/layout/_about.scss
> +        letter-spacing: 0.04em;
забрав

2023-01-15 18:30 UTC, Turt1ePower commented on src/partials/about.html
> +    <!-- <div class="about__images">
комменты надо удалить

2023-01-15 18:31 UTC, Turt1ePower commented on src/sass/layout/_about.scss
> +    //   background: url('../images/about/cow-mobile@2x.png'),
тут раскомментируй и убери просто знак @ тогда заработает всё

2023-01-15 18:53 UTC, MishaHryvinskyi commented on src/partials/about.html
> +    <!-- <div class="about__images">
забув... тепер видалив

2023-01-15 20:30 UTC, Turt1ePower approved these changes

2023-01-15 20:30 UTC, merged