Footer yurii
Turt1ePower/fs74-icecream-project17 pull request #12
Opened 2023-01-14 20:07 UTC by xtxthby

2023-01-15 14:58 UTC, Turt1ePower commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-github"></use>
нужно заменить пусть к иконке на 

href="./images/svg-sprite/symbol-defs.svg#icon-github"

2023-01-15 14:58 UTC, Turt1ePower commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-telegram"></use>
нужно заменить пусть к иконке на

href="./images/svg-sprite/symbol-defs.svg#icon-telegram"

2023-01-15 14:58 UTC, Turt1ePower commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-facebook"></use>
нужно заменить пусть к иконке на

href="./images/svg-sprite/symbol-defs.svg#icon-facebook"

2023-01-15 15:04 UTC, Turt1ePower commented on src/partials/footer.html
> +      <p class="footer__paragraf">Feel free to contact<a class="footer__contact" href="tel:+610383766284">+61 (0) 383 766 284</a></p>
после слова contact надо вставить пробел перед тегом ссылки

2023-01-15 15:05 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +    font-size: 14px;
для мобилки там font-size: 12px;

2023-01-15 15:06 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +    margin-right: 3px;
этого маржина нет в макете, надо удалить

2023-01-15 15:08 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +        letter-spacing: 0.02em;
letter-spacing: 0.02em; добавляется только для десктопа, поэтому его надо вложить в правило для min-width: $desktop-min

2023-01-15 15:18 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +        font-size: 12px;
для таблетки тут font-size: 14px; нужен как по макету, а маржина там нет, маржин мы даём на общий блок который оборачивает весь контент перед полосой

2023-01-15 15:19 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +.footer__paragraf {
начиная с десктопа там font-size: 16px; надо сделать правило

2023-01-15 15:22 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +.footer__text {
для мобилки до таблетки там letter-spacing: 0 по макету

2023-01-15 15:27 UTC, made-by-curiosity commented on src/sass/layout/_footer.scss
> +.footer__patent {
для мобилки надо задать letter-spacing: 0;

2023-01-15 15:29 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +        padding-top: 12px;
эти паддинги надо убрать, тут есть только нижний паддинг для общей секции внизу от конца страницы до патента

2023-01-15 15:29 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +        padding-bottom: 12px;
эти паддинги надо убрать, тут есть только нижний паддинг для общей секции внизу от конца страницы до патента

2023-01-15 15:30 UTC, Turt1ePower commented on src/sass/layout/_footer.scss
> +    font-size: 14px;
для десктопа надо сделать правило font-size: 12px; как по макету

2023-01-15 15:31 UTC, Turt1ePower requested changes
остальное описал в лс в телеграмм

2023-01-15 15:43 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +    font-size: 14px;
+

2023-01-15 15:45 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +    font-size: 14px;
+

2023-01-15 15:57 UTC, xtxthby commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-github"></use>
+

2023-01-15 15:58 UTC, xtxthby commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-telegram"></use>
+

2023-01-15 15:58 UTC, xtxthby commented on src/partials/footer.html
> +              <use href="./icons.svg/footer-symbol-defs.svg#icon-facebook"></use>
+

2023-01-15 15:58 UTC, xtxthby commented on src/partials/footer.html
> +      <p class="footer__paragraf">Feel free to contact<a class="footer__contact" href="tel:+610383766284">+61 (0) 383 766 284</a></p>
+

2023-01-15 16:53 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +    font-size: 14px;
+

2023-01-15 16:54 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +    margin-right: 3px;
+

2023-01-15 17:06 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +        letter-spacing: 0.02em;
+

2023-01-15 17:07 UTC, xtxthby commented on src/sass/layout/_footer.scss
> +        font-size: 12px;
+

2023-01-16 10:11 UTC, Turt1ePower approved these changes

2023-01-16 10:11 UTC, merged