Feature/products
Turt1ePower/fs74-icecream-project17 pull request #2
Opened 2023-01-12 18:52 UTC by Darina33

2023-01-12 21:53 UTC, Turt1ePower commented on src/sass/layout/_products.scss
> +        line-height: 1.2;
тут лучше 1.22 сделать, когда делишь, округляй до сотых

2023-01-12 21:56 UTC, Turt1ePower commented on src/sass/layout/_products.scss
> +        line-height: 1.26;
а тут лучше 1.27, ибо при делении там выходит 1.26666+, лучше округлять в большую сторону после 5, но это так, если уже по полной супер правильно делать =)

2023-01-12 21:57 UTC, Turt1ePower commented on src/sass/layout/_products.scss
> +        font-family: 'Seymour One';
font-family: 'Seymour One', sans-serif;

в конце надо добавлять обязательно общий шрифт если наш не подключится

2023-01-12 22:47 UTC, Turt1ePower commented on src/sass/layout/_products.scss
> +
для десктопа там падинги меняются 76 и 44, нужно медиаправило для 1200

2023-01-12 22:50 UTC, Turt1ePower commented on src/partials/products.html
> +      <button type="button" class="products__button"><svg width="40" height="16"><use href="..//..//src/images/products/symbol-defs.svg#icon-arrow"></use></svg></button>
думаю нужно еще четкие размеры кнопам дать

2023-01-13 07:44 UTC, Darina33 commented on src/sass/layout/_products.scss
> +
перевірила, там 60

2023-01-13 10:28 UTC, Turt1ePower commented on src/sass/layout/_products.scss
> +
точно, у меня в макете съехало почему-то, в общем 60

2023-01-13 10:49 UTC, Turt1ePower requested changes
чуть больше кнопку сделать надо и добавить изменение цвета при хавере и фокусе

2023-01-13 10:58 UTC, Turt1ePower approved these changes

2023-01-13 10:58 UTC, merged