Advantages
Turt1ePower/fs74-icecream-project17 pull request #6
Opened 2023-01-13 19:44 UTC by Nadiia-P

2023-01-14 14:12 UTC, Nadiia-P commented
Have been corrected: 
- font-size 16px for desktop, 
- class names according to BEM, 
- section paddings, 
- icons.

2023-01-14 23:05 UTC, Turt1ePower commented on src/sass/layout/_advantages.scss
> +    margin-bottom: 24px;
для таблетки там 12 маржин по макету

2023-01-14 23:07 UTC, Turt1ePower commented on src/sass/layout/_advantages.scss
> +  letter-spacing: 0.04em;
тут с боди уже наследуется, можно убрать

2023-01-14 23:08 UTC, Turt1ePower commented on src/sass/layout/_advantages.scss
> +.advantages__number {
сюда еще нужно добавить text-transform: uppercase;

2023-01-14 23:12 UTC, Turt1ePower commented on src/sass/layout/_advantages.scss
> +  @media screen and (min-width: $tablet-min) {
для таблетки тут надо добавить line-height: 1.74; как в макете

2023-01-14 23:13 UTC, Turt1ePower commented on src/sass/layout/_advantages.scss
> +  @media screen and (min-width: $desktop-min) {
для десктопа тут надо добавить line-height: 1.76; как в макете

2023-01-14 23:19 UTC, Turt1ePower requested changes
нужно еще общие стили для before попробовать вынести выше

2023-01-15 12:59 UTC, Nadiia-P commented on src/sass/layout/_advantages.scss
> +    margin-bottom: 24px;
fixed

2023-01-15 12:59 UTC, Nadiia-P commented on src/sass/layout/_advantages.scss
> +  letter-spacing: 0.04em;
fixed

2023-01-15 13:02 UTC, Nadiia-P commented on src/sass/layout/_advantages.scss
> +.advantages__number {
fixed

2023-01-15 13:10 UTC, Nadiia-P commented on src/sass/layout/_advantages.scss
> +  @media screen and (min-width: $desktop-min) {
fixed

2023-01-15 13:10 UTC, Nadiia-P commented on src/sass/layout/_advantages.scss
> +  @media screen and (min-width: $tablet-min) {
fixed

2023-01-15 14:27 UTC, Turt1ePower approved these changes
well done!

2023-01-15 14:28 UTC, merged